reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :subs, only:[:create, :edit, :update, :new]
  end
  resource :session
  resources :subs, except:[:create, :edit, :update, :new]
  resources :posts, except:[:index]
end 

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
class Post < ApplicationRecord

	validates :title, presence:true

	belongs_to :author,
		primary_id: :id,
		foreign_key: :user_id,
		class_name: :User

	belongs_to :sub,
		primary_id: :id,
		foreign_key: :sub_id,
		class_name: :Sub
	
		# has_many :post_subs,
		# 	inverse_of: :posts

	
end

reddit_clone/app/models/post_sub.rb
class PostSub < ApplicationRecord
end

reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, presence: true

    belongs_to :moderator,
        # primary_id: :id,
        foreign_key: :user_id,
        class_name: :User

	has_many :posts,
		# primary_id: :id,
		foreign_key: :sub_id,
		class_name: :Post

    # has_many :posts,
	# 	inverse_of: :post_subs

end


#sub have many posts

reddit_clone/app/models/user.rb
class User < ApplicationRecord

	validates :username, presence: true, uniqueness:true
	validates :session_token, presence: true, uniqueness:true
	validates :password_digest, presence: true
	validates :password, length: {minimum: 6, allow_nil: true}

	attr_reader :password
	after_initialize :ensure_session_token

    has_many :subs,
        # primary_id: :id,
        foreign_key: :user_id,
        class_name: :Sub

	has_many :posts,
		# primary_id: :id,
		foreign_key: :user_id,
		class_name: :Post

	def self.find_by_credentials(username,password)
		user = User.find_by(username: username)
		return nil if user.nil?
		return user if user.is_password?(password)
	end

	def is_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def password=(password)
		@password=password
		self.password_digest= BCrypt::Password.create(password)
	end

	
	def reset_session_token!
		self.session_token= SecureRandom.base64(16)
		self.save!
		self.session_token
	end

	private
	def ensure_session_token
		self.session_token ||= SecureRandom.base64(16)
	end


end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception

	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find_by(session_token: session[:session_token])
	end

	def ensure_logged_in
		# if current_user
		# else #no current_user
		# 	redirect_to new_session_url
		# end
		redirect_to new_session_url if current_user.nil?
	end

	def login(user)
		@current_user = user
		session[:session_token] = user.reset_session_token!
	end

	def logged_in?
		!!current_user
		# !current_user.nil?
	end

    def logout
        current_user.reset_session_token!
        session[:session_token] = nil
        current_user = nil
    end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :ensure_logged_in
	before_action :is_user_the_author?, only:[:edit, :update]

	def new
		@post = Post.new
		render :new
	end

	def show
		@post = Post.find_by(id: params[:id])
		render :show
	end

	def create
		@post = Post.new(post_params)
		@post.sub_id = params[:sub_id]
		@post.user_id = current_user.id

		if @post.save
			redirect_to post_url(@post)
		else
			flash.now[:errors] = @post.errors.full_messages
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])

		if @post && is_user_the_author?	
		else
			flash.now[:error] = ["User is not the author of the post"]
		end

		render :edit
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to post_url(@post)
		else
			flash.now[:errors] = @post.errors.full_messages
			render :edit
		end
	end

	def is_user_the_author?
		@post.user_id == current_user.id
	end

	private

	def post_params
		params.require(:post).permit(:title, :url, :content)
	end
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if user 
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :ensure_logged_in
	before_action :is_user_the_moderator?, only: [:edit, :update]


    def new
        @sub = Sub.new
        render :new
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.user_id = current_user.id

        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def edit
        @sub = Sub.find(params[:id])

        if @sub.moderator == current_user
            render :edit
        else
            flash.now[:error] = ["Current user is not the moderator"]
        end

    end

	def is_user_the_moderator?
		@sub.moderator == current_user
	end

	def update
		@sub = Sub.find_by(id: params[:id])
		if @sub.update(sub_params)
			redirect_to sub_url(@sub.id)
		else
			flash.now[:errors] = @sub.errors.full_messages
			render :edit
		end
	end

    private

    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def show
		@user = User.find(params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:error] = @user.errors.full_messages
            render :new
        end
    end

    

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/subs/new.html.erb
<h1>Make a New Sub</h1>

<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<%= error %>
	<% end %>
	
<% end %>



<form action="<%= user_subs_url %>" method = "post">
	<input type="hidden" name = "authenticity_token" value = "<%= form_authenticity_token %>">

	<label>Title
		<input type="text" name="sub[title]" value="<%= @sub.title %>">
	</label>	
	<br>
	<label>Description
		<input type="text" name="sub[description]" value="<%= @sub.description %>">
	</label>	
	<br>
	<input type="submit" value="Create Sub!">



</form>

reddit_clone/app/views/users/new.html.erb
<h1>Sign Up Page</h1>

<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<%= error %>
	<% end %>
	
<% end %>



<form action="<%= users_url %>" method = "post">
	<input type="hidden" name = "authenticity_token" value = "<%= form_authenticity_token %>">

	<label>Username
		<input type="text" name="user[username]" value="<%= @user.username %>">
	</label>	
	<br>
	<label>Password
		<input type="password" name="user[password]" value="<%= @user.password %>">
	</label>	
	<br>
	<input type="submit" value="Sign Up!">



</form>

reddit_clone/app/views/users/show.html.erb
<h1>Welcome <%= @user.username %>!</h1>
<h3>Here all the user's subs</h3>

<% @user.subs.each do |sub| %>
    <%= sub.title %>
<% end %>